In [357]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import statsmodels.api as sm
from statsmodels.formula.api import ols
import math

In [358]:
df = pd.read_excel('hotelBookings.xlsx')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0.0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0.0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1.0,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1.0,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2.0,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [359]:
for kolom in df:
    print(f'{df[kolom].unique()} --{kolom}--')

['Resort Hotel'] --hotel--
[0 1] --is_canceled--
[342 737   7  13  14   0   9  85  75  23  35  68  18  37  12  72 127  78
  48  60  77  99 118  95  96  69  45  40  15  36  43  70  16 107  47 113
  90  50  93  76   3   1  10   5  17  51  71  63  62 101   2  81 368 364
 324  79  21 109 102   4  98  92  26  73 115  86  52  29  30  33  32   8
 100  44  80  97  64  39  34  27  82  94 110 111  84  66 104  28 258 112
  65  67  55  88  54 292  83 105 280 394  24 103 366 249  22  91  11 108
 106  31  87  41 304 117  59  53  58 116  42 321  38  56  49 317   6  57
  19  25 315 123  46  89  61 312 299 130  74 298 119  20 286 136 129 124
 327 131 460 140 114 139 122 137 126] --lead_time--
[2015 2099] --arrival_date_year--
['July' nan 'August'] --arrival_date_month--
[27 28 29 30 31 32 33] --arrival_date_week_number--
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31] --arrival_date_day_of_month--
[0 1 2 4 3 6] --stays_in_weekend_nights--
[ 0.   1.   2.   3.   4.   4.3  5.  10.  11.   8.   6.   7.  15.   9. ] --stays_in_week_nights--
[   2    1    3    4 3500] --adults--
[    0     1     2   200 55000    10] --children--
[0 1 2] --babies--
['             BB' 'BB' 'FB' '    HB'] --meal--
['PRT' 'GBR' 2 'USA' 'ESP' 'IRL' 'FRA' nan '  ROU' 'NOR' 'OMN' 'ARG' 'POL'
 'DEU' 'BEL' 'CHE' 3 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST'
 'CZE' 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX'] --country--
['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary'
 'G  ROUps'] --market_segment--
['Direct' 'Corporate' 'TA/TO'] --distribution_channel--
[0] --is_repeated_guest--
[0] --previous_cancellations--
[0] --previous_bookings_not_canceled--
['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L'] --reserved_room_type--
['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H'] --assigned_room_type--
[3 4 0 1 2 5] --booking_changes--
['No Deposit'] --deposit_type--
[ nan 304. 240. 303.  15. 241.   8. 250. 115.   5. 175. 134. 156. 243.
 242.   3. 105.  40. 147. 306. 184.  96.   2. 127.  95. 146.   9. 177.
   6. 143. 244. 149. 167. 300. 171. 305.  67. 196. 152. 142. 261. 104.
  36.] --agent--
[ nan 110. 113. 270. 178. 240. 154. 144.] --company--
[0] --days_in_waiting_list--
['Transient' 'Contract' 'Transient-Party' 'G  ROUp'] --customer_type--
[  0.    75.    98.   107.   103.    82.   105.5  123.   145.    97.
 154.77  94.71  97.5   88.2  107.42 153.    97.29  84.67  99.67  94.95
  63.6   79.5   94.    87.3   62.    63.86 108.3   65.5  108.8  137.
 117.81 110.7   58.95  82.88  82.35 119.35  67.58  56.01 147.   117.9
 135.   133.   136.33 110.5  110.3   73.8   91.5  114.5   90.9  122.
  85.86  55.68 124.   111.15 134.73  92.45 108.73 131.   117.   196.54
  99.3   90.95  92.67  71.55  96.49  85.8   96.3  163.   172.   139.
  67.24 116.5  149.   105.   113.    85.1   89.    80.1  101.   167.
 225.    85.59 164.2  114.    98.4  175.   124.45  74.07 134.1  171.32
 210.   117.8  117.63 185.    71.    47.25 151.   120.6  157.1   91.37
  73.    93.6   83.5  185.5  109.8  195.   193.   150.   126.65 146.
  61.   104.72  66.42  77.96 112.    89.68 155.   130.1  100.1  105.08
  65.42  75.46 119.25 118.13 120.   197.   165.   149.4  106.84 161.
 134.43 144.43 152.   125.54 133.83 159.75 112.2  110.6  105.9   95.27
 108.83 153.96  90.67 126.67 144.4   99.5  139.4   89.97 144.9  100.
 104.68 166.   111.25 213.75 178.   113.9  129.29 169.    93.   132.29
 117.22 164.57 105.71 126.   148.3  125.22 130.   133.16  78.84  90.71
 120.2  128.   130.05 103.8  196.   175.71 119.7  100.86  64.   110.
 132.8  144.2  107.2  163.8   98.5  130.5  184.6  181.22 100.2  134.25
  83.09 134.     8.   136.2  101.8  127.   161.5  230.67  65.7  180.
 168.57 107.67  96.9   73.41 109.9  187.5  132.44 106.9  131.86 216.13
 190.33  98.75 148.23 123.2  198.   103.5  135.6  184.   151.33 121.33
 150.2   75.44 160.   127.25 164.   144.5  155.5  107.6  133.75  84.8
 125.   132.3   92.   194.9  118.5  192.   128.27 126.3  154.   136.
 116.33 147.67 168.3  137.75 132.6  157.   132.5   98.02 173.   249.
 186.5   95.   241.5  177.   153.73 115.   127.03 128.25 124.5  154.5
 110.53 158.5  131.37 117.71 117.84 116.85 129.16 214.   135.2  179.1
 111.65 104.   133.17 141.33 121.01 240.64 167.5  152.43 148.34 172.93
 192.5  111.2  141.6  200.   207.   163.33 151.86  95.57 112.05 103.18
 119.75 167.69 178.4  194.   101.46 217.05 112.5  233.   222.67 149.7
 161.25 159.2  163.29 121.98 118.   158.77 142.03 240.   176.   131.63
 233.05  90.12 114.25  88.55  95.02 209.   174.01 124.2  162.   133.2
 167.2  183.45 159.6  219.43 102.72 114.85 138.8  115.5  108.54 165.4
 188.   186.   141.65  99.24 108.06 148.63 250.33 146.67 280.74 137.8
 125.89 126.71 154.8  219.5  111.92  57.6  157.8  170.33 118.06 202.
 252.   211.   237.   188.29 177.14 222.14 127.82 194.14 144.53 193.13
 210.78 174.7  135.53 144.   162.5  209.6  195.5  163.5  180.28 174.76
 159.   104.55 144.76 205.   220.55 162.14  77.54 221.   230.5  241.
 187.8  171.9  148.25 183.   242.6  168.71 268.   149.2  217.2  239.3
 181.5  181.9  267.   226.   191.   277.5  133.5  154.38 121.39 250.
 208.   181.   157.59 211.75 246.   200.71 276.43 228.   138.   165.69
 127.31 211.5  210.33 145.4  101.25 179.38] --adr--
[0 1 2] --required_car_parking_spaces--
[0 1 3 2 4] --total_of_special_requests--
['Check-Out' 'Canceled' 'No-Show'] --reservation_status--
<DatetimeArray>
['2015-07-01 00:00:00', '2015-07-02 00:00:00', '2015-07-03 00:00:00',
 '2015-05-06 00:00:00', '2015-04-22 00:00:00', '2015-06-23 00:00:00',
 '2015-07-05 00:00:00', '2015-07-06 00:00:00', '2015-07-07 00:00:00',
 '2015-07-08 00:00:00',
 ...
 '2015-08-09 00:00:00', '2015-08-15 00:00:00', '2015-08-11 00:00:00',
 '2015-03-28 00:00:00', '2015-08-14 00:00:00', '2015-08-12 00:00:00',
 '2015-08-16 00:00:00', '2015-05-16 00:00:00', '2015-08-21 00:00:00',
 '2015-08-13 00:00:00']
Length: 108, dtype: datetime64[ns] --reservation_status_date--

In [360]:
#unieke waarde maken

df.loc[df['arrival_date_year']== 2099, 'arrival_date_year'] = 2015

In [361]:

df = df.dropna(subset=['arrival_date_month'])
df = df.dropna(subset = ['country'])

for kolom in df:
    print(f'{kolom} -----{df[kolom].isna().sum()}')

hotel -----0
is_canceled -----0
lead_time -----0
arrival_date_year -----0
arrival_date_month -----0
arrival_date_week_number -----0
arrival_date_day_of_month -----0
stays_in_weekend_nights -----0
stays_in_week_nights -----0
adults -----0
children -----0
babies -----0
meal -----0
country -----0
market_segment -----0
distribution_channel -----0
is_repeated_guest -----0
previous_cancellations -----0
previous_bookings_not_canceled -----0
reserved_room_type -----0
assigned_room_type -----0
booking_changes -----0
deposit_type -----0
agent -----94
company -----972
days_in_waiting_list -----0
customer_type -----0
adr -----0
required_car_parking_spaces -----0
total_of_special_requests -----0
reservation_status -----0
reservation_status_date -----0

In [362]:
df['adults'].unique()
df.loc[df['adults']==3500, 'adults'].count()
df = df.drop(df[df['adults']==3500].index)

In [363]:
df['children'].unique()
df = df.drop(df[df['children']==55000].index)

In [364]:
df['stays_in_week_nights'].unique()
df['stays_in_week_nights'] = df['stays_in_week_nights'].astype(int)
df['stays_in_week_nights'].unique()

array([ 0,  1,  2,  3,  4,  5, 11,  8, 10,  6,  7, 15,  9])

In [365]:
df['meal'] = df['meal'].str.strip()

In [366]:

df = df[df['country'] != 3]
df['country'] = df['country'].str.strip()
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:

df['market_segment'] = df['market_segment'].str.strip()
df.loc[df['market_segment'] == 'G  ROUps', 'market_segment'] ='Groups'

df['market_segment'].unique()

array(['Corporate', 'Online TA', 'Direct', 'Offline TA/TO', 'Groups'],
      dtype=object)

In [ ]:
df.drop_duplicates()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Resort Hotel,0,34,2015,August,33,9,2,2,2,...,No Deposit,240.0,NaN,0,Transient,211.00,0,1,Check-Out,2015-08-13
996,Resort Hotel,0,82,2015,August,33,9,2,2,2,...,No Deposit,240.0,NaN,0,Transient,154.00,0,0,Check-Out,2015-08-13
997,Resort Hotel,1,65,2015,August,33,9,2,3,2,...,No Deposit,240.0,NaN,0,Transient,145.40,0,0,Canceled,2015-06-22
998,Resort Hotel,1,129,2015,August,33,9,2,3,1,...,No Deposit,240.0,NaN,0,Transient,101.25,0,0,Canceled,2015-04-06
999,Resort Hotel,0,55,2015,August,33,9,2,4,2,...,No Deposit,242.0,NaN,0,Transient,179.38,0,0,Check-Out,2015-08-15

In [ ]:
# company
df['company'] = df['company'].astype('Int64')
df['company'].unique()

<IntegerArray>
[<NA>, 110, 113, 270, 178, 240, 154, 144]
Length: 8, dtype: Int64

In [ ]:
df['customer_type'].unique()
df['customer_type'] = df['customer_type'].str.replace('G  ROUp', 'Group')
df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [374]:
df['reservation_status_date'].unique()

<DatetimeArray>
['2015-07-01 00:00:00', '2015-07-02 00:00:00', '2015-07-03 00:00:00',
 '2015-05-06 00:00:00', '2015-04-22 00:00:00', '2015-06-23 00:00:00',
 '2015-07-05 00:00:00', '2015-07-06 00:00:00', '2015-07-07 00:00:00',
 '2015-07-08 00:00:00',
 ...
 '2015-08-11 00:00:00', '2015-08-10 00:00:00', '2015-03-28 00:00:00',
 '2015-08-14 00:00:00', '2015-08-12 00:00:00', '2015-05-20 00:00:00',
 '2015-08-16 00:00:00', '2015-05-16 00:00:00', '2015-08-21 00:00:00',
 '2015-08-13 00:00:00']
Length: 108, dtype: datetime64[ns]

In [371]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')